---
# tasks file for createUser

---

- name: Create user
  user:
    name: {{ remote_user }}
    state: present
    shell: /bin/bash

- name: Deploy SSH public Key
  ansible.posix.authorized_key:
    user: {{ remote_user }}
    state: present
    key: {{ pub_key }}
