---
# tasks file for wazuh

# Создание директорий для volumes
- name: Create directory for volumes
  file: path={{ item.path }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} state=directory
  loop:
    - { path: "{{ wazuh_dir }}/config/wazuh_indexer_ssl_certs", owner: "root", group: "root", mode: "755" }
    - { path: "{{ wazuh_dir }}/wazuh-manager/wazuh_api_configuration", owner: "root", group: "root", mode: "755" }
    - { path: "{{ wazuh_dir }}/wazuh-manager/wazuh_etc", owner: "root", group: "root", mode: "755" }
    - { path: "{{ wazuh_dir }}/wazuh-manager/wazuh_logs", owner: "root", group: "root", mode: "755" }
    - { path: "{{ wazuh_dir }}/wazuh-manager/wazuh_queue", owner: "root", group: "root", mode: "755" }
    - { path: "{{ wazuh_dir }}/wazuh-manager/wazuh_var_multigroups", owner: "root", group: "root", mode: "755" }
    - { path: "{{ wazuh_dir }}/wazuh-manager/wazuh_integrations", owner: "root", group: "root", mode: "755" }
    - { path: "{{ wazuh_dir }}/wazuh-manager/wazuh_active_response", owner: "root", group: "root", mode: "755" }
    - { path: "{{ wazuh_dir }}/wazuh-manager/wazuh_agentless", owner: "root", group: "root", mode: "755" }
    - { path: "{{ wazuh_dir }}/wazuh-manager/wazuh_wodles", owner: "root", group: "root", mode: "755" }
    - { path: "{{ wazuh_dir }}/wazuh-manager/filebeat_etc", owner: "root", group: "root", mode: "755" }
    - { path: "{{ wazuh_dir }}/wazuh-manager/filebeat_var", owner: "root", group: "root", mode: "755" }
    - { path: "{{ wazuh_dir }}/wazuh-dashboard", owner: "root", group: "root", mode: "755" }
    - { path: "{{ wazuh_dir }}/wazuh-indexer", owner: "root", group: "root", mode: "755" }


- name: add files
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
  loop:
    - { src: "certs.yml", dest: "{{ wazuh_dir }}/config/certs.yml", mode: "755" }


# Создание и запуск docker-compose файла
- name: wazuh
  community.docker.docker_compose:
    project_name: wazuh
    definition:
      version: '3.7'
      services:
        wazuh.generator:
          image: "{{ generator.repo }}:{{ generator.tag }}"
          volumes:
            - '{{ wazuh_dir }}/config/wazuh_indexer_ssl_certs/:/certificates/'
            - '{{ wazuh_dir }}/config/certs.yml:/config/certs.yml'
        wazuh.manager:
          image: "{{ manager.repo }}:{{ manager.tag }}"
          hostname: wazuh.manager
          restart: unless-stopped
          ports:
            - "1514:1514"
            - "1515:1515"
            - "514:514/udp"
            - "55000:55000"
          environment:
            - INDEXER_URL=https://wazuh.indexer:9200
            - INDEXER_USERNAME={{ indexer.login }}
            - INDEXER_PASSWORD={{ indexer.password}}
            - FILEBEAT_SSL_VERIFICATION_MODE=full
            - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
            - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
            - SSL_KEY=/etc/ssl/filebeat.key
            - API_USERNAME=wazuh-wui
            - API_PASSWORD=MyS3cr37P450r.*-
          volumes:
            - '{{ wazuh_dir }}/wazuh-manager/wazuh_api_configuration:/var/ossec/api/configuration'
            - '{{ wazuh_dir }}/wazuh-manager/wazuh_etc:/var/ossec/etc'
            - '{{ wazuh_dir }}/wazuh-manager/wazuh_logs:/var/ossec/logs'
            - '{{ wazuh_dir }}/wazuh-manager/wazuh_queue:/var/ossec/queue'
            - '{{ wazuh_dir }}/wazuh-manager/wazuh_var_multigroups:/var/ossec/var/multigroups'
            - '{{ wazuh_dir }}/wazuh-manager/wazuh_integrations:/var/ossec/integrations'
            - '{{ wazuh_dir }}/wazuh-manager/wazuh_active_response:/var/ossec/active-response/bin'
            - '{{ wazuh_dir }}/wazuh-manager/wazuh_agentless:/var/ossec/agentless'
            - '{{ wazuh_dir }}/wazuh-manager/wazuh_wodles:/var/ossec/wodles'
            - '{{ wazuh_dir }}/wazuh-manager/filebeat_etc:/etc/filebeat'
            - '{{ wazuh_dir }}/wazuh-manager/filebeat_var:/var/lib/filebeat'
            - '{{ wazuh_dir }}/config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem'
            - '{{ wazuh_dir }}/config/wazuh_indexer_ssl_certs/wazuh.manager.pem:/etc/ssl/filebeat.pem'
            - '{{ wazuh_dir }}/config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key'
            - '{{ wazuh_dir }}/config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf'
        wazuh.indexer:
          image: "{{ indexer.repo }}:{{ indexer.tag }}"
          hostname: wazuh.indexer
          restart: always
          ports:
            - "9200:9200"
          environment:
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
          ulimits:
            memlock:
              soft: -1
              hard: -1
            nofile:
              soft: 65536
              hard: 65536
          volumes:
            - '{{ wazuh_dir }}/wazuh-manager/wazuh-indexer-data:/var/lib/wazuh-indexer'
            - '{{ wazuh_dir }}/config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/config/certs/root-ca.pem'
            - '{{ wazuh_dir }}/config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/config/certs/wazuh.indexer.key'
            - '{{ wazuh_dir }}/config/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/config/certs/wazuh.indexer.pem'
            - '{{ wazuh_dir }}/config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/config/certs/admin.pem'
            - '{{ wazuh_dir }}/config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/config/certs/admin-key.pem'
            - '{{ wazuh_dir }}/config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/config/opensearch.yml'
            - '{{ wazuh_dir }}/config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/internal_users.yml'
        wazuh.dashboard:
          image: "{{ dashboard.repo }}:{{ dashboard.tag }}"
          hostname: wazuh.dashboard
          restart: always
          ports:
            - 443:5601
          environment:
            - INDEXER_USERNAME={{ indexer.login }}
            - INDEXER_PASSWORD={{ indexer.password }}
            - WAZUH_API_URL=https://wazuh.manager
            - API_USERNAME=wazuh-wui
            - API_PASSWORD=MyS3cr37P450r.*-
          volumes:
            - '{{ wazuh_dir }}/config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem'
            - '{{ wazuh_dir }}/config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem'
            - '{{ wazuh_dir }}/config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem'
            - '{{ wazuh_dir }}/config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml'
            - '{{ wazuh_dir }}/config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml'

- name: docker network creation
  docker_network:
    name: wazuh
    connected:
      - wazuh_wazuh.manager_1
      - wazuh_wazuh.indexer_1
      - wazuh_wazuh.dashboard_1
