---
# Installing docker

# Установка необходимых зависимостей
- name: install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - parallel
    update_cache: yes

# Добавление apt key для управления ключами аутентификации пакетов
- name: add apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

# Добавление репозиториия с докером
- name: add docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable

# Устанока docker, docker-compose и его зависимостей
- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose
      - containerd.io
    update_cache: yes

# Добавление привилегий на пользованием docker вновь созданному пользователю
- name: add userpermissions
  shell: "usermod -aG docker '{{ remote_user }}'"
