---

# Создание пользователя
- name: Create user
  user:
    name: "{{ remote_user }}"
    state: present
    shell: /bin/bash

# Деплой публичного ключа созданного пользователя на удаленную машину
- name: Deploy SSH public Key
  ansible.posix.authorized_key:
    user: "{{ remote_user }}"
    state: present
    key: "{{ pub_key }}"

# Создание связки ключей для дальнейшей аутентификации в Gitlab
- name: generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: "/home/{{ remote_user }}/.ssh/id_rsa"

# Получение публчного ключа
- name: Get public key
  command: cat "/home/{{ remote_user }}/.ssh/id_rsa.pub"
  register: result

- debug: msg="{{ result.stdout }}"
